name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # lehetővé teszi, hogy "kézzel" elindítsam a folyamatot
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: generate image tag
      run: |
        echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - uses: actions/checkout@v4
    - name: Checkout repository
      run: | 
        docker build . --file Dockerfile  --tag ghcr.io/mzalan/cicd-k8s-13ab:$IMAGE_TAG
        docker login ghcr.io -u mzalan -p ${{ secrets.GHCR_TOKEN }}
        docker push ghcr.io/mzalan/cicd-k8s-13ab:$IMAGE_TAG

        sed -i 's|image: ghcr.io/mzalan/cicd-k8s-13ab:.*|image: ghcr.io/mzalan/cicd-k8s-13ab:'"$IMAGE_TAG"'|' test-deployment.yaml
        
        git add test-deployment.yaml
        git commit -m "update K8S deployment file"
        git push

        mkdir -p ~/.kube
        echo "${{ secrets.JEDLIK_K8S_CONFIG }}" | base64 -d > ~/.kube/config
        kubectl apply -f ./test-deployment.yaml


#config fájl base64-be kódolása
# $bytes = [System.IO.File]::ReadAllBytes("$env:USERPROFILE/.kube/config")
# [System.Convert]::ToBase64String($bytes) 
        
# -> elmentettük egy JEDLIK_K8S_CONFIG secretbe

    

#TODO: kubclt apply 
#      config-nak secretbe másolása

