name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # lehetővé teszi, hogy "kézzel" elindítsam a folyamatot
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: generate image tag
      run: |
        echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - uses: actions/checkout@v4
    - name: Checkout repository
      run: | 
        docker build . --file Dockerfile  --tag ghcr.io/marquetant-zalan/cicd-k8s-13a-test-cicd-13ab:$IMAGE_TAG
        docker login ghcr.io -u marquetant-zalan -p ${{ secrets.GHCR_TOKEN }}
        docker push ghcr.io/marquetant-zalan/test-cicd-13ab:$IMAGE_TAG
    

